import { createHash } from 'node:crypto';
import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * A cassette is one recorded live run, kept so the tooling can be regression-tested without paying
 * for the model again.
 *
 * What is recorded is the isolated project's Git history, not the model's responses. That choice is
 * forced by what actually exists: `run-engine.mjs` passes `--no-session-persistence`, so no
 * tool-call transcript is written anywhere, and a recorded response could not reproduce the file
 * system state even if one were. What the model did to the project *is* recorded, exactly, by the
 * commit the harness already makes after every Stage — so a finished run is already a tape, and
 * this only packages it.
 *
 * Replaying therefore exercises the CLI, the Gates, the control plane, the Approval and
 * work-package protocols, archive, and the harness itself. It cannot exercise whether a Skill is
 * comprehensible or whether an Agent obeys it, which is why `scaffold` below exists: a cassette
 * carries the fingerprint of the Scaffold it was recorded against, and replaying against a changed
 * Scaffold is refused rather than silently passed.
 */

const repositoryRoot = path.resolve(fileURLToPath(new URL('../..', import.meta.url)));
export const cassettesRoot = path.join(repositoryRoot, 'tests', 'live-engine', 'cassettes');

export const cassetteFiles = (name) => ({
  manifest: path.join(cassettesRoot, `${name}.json`),
  bundle: path.join(cassettesRoot, `${name}.bundle`),
});

/**
 * Fingerprints everything an Agent reads that this repository controls.
 *
 * `scaffold/files.sha256` is already a digest of every payload file — Skills, Flows, Gates, Rules,
 * policies, agents — so hashing it covers the whole surface in one value, and it is regenerated by
 * the same script `check:scaffold` verifies. If a Skill's wording changes, this changes, and the
 * cassette stops being evidence about the current product.
 */
export function scaffoldFingerprint() {
  const manifest = path.join(repositoryRoot, 'scaffold', 'files.sha256');
  return `sha256:${createHash('sha256').update(readFileSync(manifest)).digest('hex')}`;
}

/**
 * Which commits are the model's, read off the messages the harness writes.
 *
 * The subjects already separate the two kinds of work — a Stage the Agent drove versus an operation
 * the harness performed on its behalf — so replay can substitute exactly the former and genuinely
 * re-execute the latter. Anything unrecognised is treated as a harness commit, which is the safe
 * default: a harness step re-run on replay is tested, a model step re-run would call the model.
 */
export function modelStepFromSubject(subject, scenario) {
  const complete = new RegExp(`^Live engine stage complete: ${scenario}:(.+)$`).exec(subject);
  if (complete) return complete[1];
  const continuation = /^Live engine continuation: (.+) delivery observed$/.exec(subject);
  if (continuation) return `${continuation[1]}-delivered`;
  const checkpoint = /^Live engine standalone checkpoint: (.+)$/.exec(subject);
  if (checkpoint) return checkpoint[1];
  return null;
}

export function readCassette(name) {
  const files = cassetteFiles(name);
  if (!existsSync(files.manifest)) {
    throw new Error(`No cassette named "${name}". Record one with: node tests/live-engine/record-cassette.mjs --scenario ${name}`);
  }
  const manifest = JSON.parse(readFileSync(files.manifest, 'utf8'));
  if (!existsSync(files.bundle)) throw new Error(`Cassette ${name} has a manifest but no bundle at ${files.bundle}.`);
  return { ...manifest, files };
}

/**
 * Refuses a replay whose result would no longer mean anything.
 *
 * A cassette records what one model did when it read one particular set of Skills. Change those and
 * the recording stops being a prediction of what an Agent would do now, so a green replay would be
 * evidence about a Scaffold that no longer exists. Re-record instead — that is the "must re-run
 * live after changing a Skill" rule, enforced rather than remembered.
 */
export function assertCassetteStillApplies(cassette) {
  const current = scaffoldFingerprint();
  if (cassette.scaffold !== current) {
    throw new Error(
      `Cassette "${cassette.scenario}" was recorded against a different Scaffold.\n`
      + `  recorded: ${cassette.scaffold}\n  current:  ${current}\n`
      + 'A Skill, Flow, Gate, Rule or policy changed since, so replaying it would test the tooling '
      + 'against instructions no Agent has ever been given. Re-record with a live run:\n'
      + `  node tests/live-engine/run-matrix.mjs --scenario ${cassette.scenario} --cli-source local\n`
      + `  node tests/live-engine/record-cassette.mjs --scenario ${cassette.scenario}`,
    );
  }
}
