import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Diagnostic } from '../types.js';
import { XForgeError, diagnostic } from '../core/errors.js';

/**
 * What a diagnostic code means, without going to the source.
 *
 * A field report's phrasing was "key semantics are only readable in the source", and it is accurate:
 * this product can emit several hundred codes, the message is written at the call site, and anything
 * a reader wants beyond the one sentence they just saw is in a comment they cannot reach. An Agent
 * that meets `XFORGE_WORK_PACKAGE_GOVERNANCE_IN_RANGE` has one line and no way to ask for more.
 *
 * This answers from a catalogue frozen into `dist` at build time — see `scripts/build-diagnostics.mjs`
 * for why it cannot be a runtime scan. Deliberately no new prose: every code's messages are already
 * written, and they are long and specific because that is this codebase's style. Inventing a second
 * description per code would be three hundred entries nobody has written, going stale against the
 * messages they are supposed to explain.
 *
 * What it adds over the one line a reader already has:
 *
 * - **Every message the code can carry.** One code is raised from more than one place, and which of
 *   them a reader has *not* met is what tells them the code has another cause.
 * - **Its severity, and where it is raised from.** A code that is `warning` in one place and `error`
 *   in another is a real thing to know before deciding whether it blocks.
 */
const packageRoot = path.resolve(fileURLToPath(new URL('../..', import.meta.url)));

interface CatalogueEntry {
  code: string;
  severities: string[];
  sources: Array<{ file: string; line: number; message: string; hasPath: boolean }>;
}

async function loadCatalogue(): Promise<CatalogueEntry[]> {
  const target = path.join(packageRoot, 'dist', 'diagnostics.json');
  try {
    return (JSON.parse(await readFile(target, 'utf8')) as { codes: CatalogueEntry[] }).codes;
  } catch (error) {
    throw new XForgeError(diagnostic(
      'XFORGE_EXPLAIN_CATALOGUE_MISSING',
      `The diagnostic catalogue is not in this build (${(error as Error).message}). It is generated by \`npm run build\`; a package missing it was not built by the published pipeline.`,
    ));
  }
}

/** Codes whose name is one edit away, so a typed code that misses says what was meant. */
function near(code: string, known: string[]): string[] {
  const upper = code.toUpperCase();
  return known.filter((candidate) => candidate.includes(upper) || upper.includes(candidate)).slice(0, 5);
}

export async function executeExplain(options: { code: string }): Promise<{
  data: Record<string, unknown>;
  diagnostics: Diagnostic[];
}> {
  const codes = await loadCatalogue();
  const wanted = options.code.trim().toUpperCase();
  const entry = codes.find((candidate) => candidate.code === wanted);

  if (!entry) {
    const suggestions = near(wanted, codes.map((candidate) => candidate.code));
    throw new XForgeError(diagnostic(
      'XFORGE_EXPLAIN_CODE_UNKNOWN',
      `No diagnostic code ${wanted} in this build's catalogue of ${codes.length}.${suggestions.length > 0 ? ` Did you mean: ${suggestions.join(', ')}?` : ''} Codes are exact and always begin with XFORGE_.`,
    ));
  }

  return {
    data: {
      code: entry.code,
      severities: entry.severities,
      /* Every wording, not the first: which one a reader has not met is the useful half. */
      messages: entry.sources.map((source) => ({ message: source.message, raisedIn: `${source.file}:${source.line}`, carriesPath: source.hasPath })),
    },
    diagnostics: [],
  };
}

/** The readable form: the code, what it costs, and every way it can be worded. */
export function renderExplainText(data: Record<string, unknown>): string {
  const messages = data.messages as Array<{ message: string; raisedIn: string; carriesPath: boolean }>;
  const lines: string[] = [];
  lines.push(`${String(data.code)}  —  ${(data.severities as string[]).join(' / ')}`);
  lines.push('');
  lines.push(messages.length === 1
    ? 'It is raised from one place, and this is what it says:'
    : `It is raised from ${messages.length} places, each saying something slightly different:`);
  for (const entry of messages) {
    lines.push('');
    lines.push(`  ${entry.raisedIn}${entry.carriesPath ? '' : '   (carries no file path)'}`);
    lines.push(`    ${entry.message}`);
  }
  return `${lines.join('\n')}\n`;
}
