apiVersion: xforge.dev/v1alpha2
kind: Scaffold
metadata:
  version: 0.7.12
protocol: "2"
payload: payload
integrity:
  algorithm: sha256
  manifest: files.sha256
xforgeCompatibility:
    protocol: "2"
